"""Generate the macro-language v2 parser from its ANTLR grammar.

    python tools/gen_macro_parser.py            # regenerate
    python tools/gen_macro_parser.py --check    # exit 1 if out of date

The grammar is `docs/macro-spec/grammar/MacroLexer.g4` + `MacroParser.g4`
(Patrick's, the single source: docs/macro-spec/MACRO_SPEC.md sec1 task 3).
The Python target is generated into `floorplanner/macro2/_generated/` and
COMMITTED (his ruling, 0212-report.md sec3), so CI and users need only the
pinned `antlr4-python3-runtime` -- never Java or the ANTLR tool.

That leaves one way for the two to drift: someone edits a `.g4` and does not
regenerate. `GRAMMAR.sha256`, written here beside the generated code, is the
hash of the two grammar files; `tests/test_macro2_language.py` recomputes it,
so a grammar edit without regeneration goes red WITHOUT needing Java.

ANTLR 4.11.1, the version the spec names and the grammar was validated with;
`antlr4-python3-runtime` is pinned to the same number. Needs `java` on PATH.
The tool jar is fetched once into `~/.cache/floorplanner/` (override with the
`ANTLR_JAR` environment variable).
"""
import hashlib
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import urllib.request

ANTLR_VERSION = "4.11.1"
ROOT = pathlib.Path(__file__).resolve().parent.parent
GRAMMAR_DIR = ROOT / "docs" / "macro-spec" / "grammar"
GRAMMARS = ("MacroLexer.g4", "MacroParser.g4")
OUT_DIR = ROOT / "floorplanner" / "macro2" / "_generated"
GENERATED = ("MacroLexer.py", "MacroParser.py", "MacroParserVisitor.py")
HASH_FILE = "GRAMMAR.sha256"
INIT = ('"""GENERATED by ANTLR %s from docs/macro-spec/grammar/*.g4 -- do not edit.\n'
        'Regenerate with `python tools/gen_macro_parser.py`."""\n' % ANTLR_VERSION)


def grammar_hash() -> str:
    """SHA-256 over the two grammar files, line endings normalised to LF so a
    checkout's CRLF conversion cannot change it."""
    h = hashlib.sha256()
    for name in GRAMMARS:
        data = (GRAMMAR_DIR / name).read_bytes().replace(b"\r\n", b"\n")
        h.update(name.encode("ascii") + b"\0" + data + b"\0")
    return h.hexdigest()


def recorded_hash() -> str:
    p = OUT_DIR / HASH_FILE
    return p.read_text(encoding="ascii").strip() if p.exists() else ""


def _jar() -> pathlib.Path:
    env = os.environ.get("ANTLR_JAR")
    if env:
        return pathlib.Path(env)
    cache = pathlib.Path.home() / ".cache" / "floorplanner"
    jar = cache / f"antlr-{ANTLR_VERSION}-complete.jar"
    if not jar.exists():
        cache.mkdir(parents=True, exist_ok=True)
        url = f"https://www.antlr.org/download/antlr-{ANTLR_VERSION}-complete.jar"
        print(f"fetching {url}")
        urllib.request.urlretrieve(url, jar)
    return jar


def generate() -> None:
    if shutil.which("java") is None:
        sys.exit("java is not on PATH -- the ANTLR tool needs it")
    with tempfile.TemporaryDirectory() as tmp:
        # run IN the grammar directory with bare file names, so the
        # "# Generated from ..." header carries no machine-specific path
        subprocess.run(
            ["java", "-jar", str(_jar()), "-Dlanguage=Python3", "-visitor",
             "-no-listener", "-o", tmp, *GRAMMARS],
            cwd=GRAMMAR_DIR, check=True)
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        for name in GENERATED:
            text = (pathlib.Path(tmp) / name).read_text(encoding="utf-8")
            (OUT_DIR / name).write_text(text, encoding="utf-8", newline="\n")
    (OUT_DIR / "__init__.py").write_text(INIT, encoding="utf-8", newline="\n")
    (OUT_DIR / HASH_FILE).write_text(grammar_hash() + "\n", encoding="ascii",
                                     newline="\n")
    print(f"generated {', '.join(GENERATED)} into {OUT_DIR.relative_to(ROOT)}")


def main() -> int:
    if "--check" in sys.argv[1:]:
        ok = recorded_hash() == grammar_hash()
        print("generated parser is " + ("current" if ok else "OUT OF DATE -- "
              "run python tools/gen_macro_parser.py"))
        return 0 if ok else 1
    generate()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
