#!/usr/bin/env python3
"""Read per-task progress entries in `docs/progress/tasks/` and regenerate
`docs/progress/tasks/INDEX.md` from them.

THE INDEX IS GENERATED, NEVER HAND-EDITED -- same discipline as
`tools/defects_index.py`. Built per 0104-ruling.md SS5 tier 1: **per-task
files, not a shared append-only tail.** `docs/progress/README.md`'s own
"An append-only shared file serialises parallel branches" section measured
that every merge conflict in one GREEN batch was in exactly that shape --
two branches each appending an entry to `side-tasks.md`'s tail. A generated,
one-writer-per-file index cannot collide the same way: two new task files
never touch the same line, and this script -- not a hand edit -- is what
lists them.

    python tools/progress_index.py              # rewrite INDEX.md
    python tools/progress_index.py --check       # fail if it would change

Each task file is `docs/progress/tasks/YYYY-MM-DD-<slug>.md`. The filename
date is the sort key -- not git commit order (not reconstructible after a
rebase or squash) and not mtime (not portable across a clone).

FRONT LINE FORMAT, not YAML: a `# ` title, then the first non-blank line
after it must be `**YYYY-MM-DD**, branch \\`<name>\\`.` with an optional
trailing ` handoff: NNNN`. Same reasoning as `defects_index.py`'s own
docstring for its hand-rolled front-matter reader: the shape is small and
fixed, and a strict reader here catches malformation a permissive one would
silently reinterpret.

Historical entries (the phase-numbered files, `side-tasks.md`,
`phase-5.md`, `furnishings.md`) are NOT migrated here and are out of this
script's scope on purpose -- they are frozen narrative, nothing appends to
their tail going forward, and re-splitting settled history for a conflict
it can no longer have would only add risk. This directory is where NEW
entries land from now on; see `docs/progress/README.md`.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TASKS = ROOT / "docs" / "progress" / "tasks"
INDEX = TASKS / "INDEX.md"

META_RE = re.compile(
    r"^\*\*(\d{4}-\d{2}-\d{2})\*\*,\s*branch\s*`([^`]+)`\."
    r"(?:\s*handoff:\s*(\d{4}))?\s*$")
FNAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")


def parse(path):
    """Strict two-line-header reader. Raises ValueError with a usable
    message -- same contract as `defects_index.parse`."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        raise ValueError(f"{path.name}: first line must be `# <title>`")
    title = lines[0][2:].strip()
    if not title:
        raise ValueError(f"{path.name}: title is empty")
    meta_line = next((ln for ln in lines[1:] if ln.strip()), "")
    m = META_RE.match(meta_line.strip())
    if not m:
        raise ValueError(
            f"{path.name}: the first non-blank line after the title must "
            "match `**YYYY-MM-DD**, branch `<name>`.` "
            "(optionally `... handoff: NNNN`), got " + repr(meta_line))
    date, branch, handoff = m.groups()
    if not FNAME_RE.match(path.name):
        raise ValueError(
            f"{path.name}: filename must be YYYY-MM-DD-<slug>.md")
    fdate = path.name[:10]
    if fdate != date:
        raise ValueError(
            f"{path.name}: filename date {fdate!r} != header date {date!r}")
    return {"title": title, "date": date, "branch": branch,
            "handoff": handoff, "path": path}


def load():
    out = []
    for path in sorted(TASKS.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        out.append(parse(path))
    return out


def render(recs):
    ordered = sorted(recs, key=lambda r: (r["date"], r["path"].name))
    lines = [
        "# Progress log — per-task index",
        "",
        "<!-- GENERATED by tools/progress_index.py — do not hand-edit. -->",
        "<!-- `python tools/progress_index.py` rewrites it; `--check` fails "
        "on drift. -->",
        "",
        f"**{len(recs)} task(s).** One file per task, no shared "
        "append-only tail (0104-ruling.md SS5 tier 1) -- see "
        "[`../README.md`](../README.md) for why, and for the historical "
        "phase-numbered files this directory does not replace.",
        "",
        "| date | title | branch | handoff |",
        "|---|---|---|---|",
    ]
    for r in ordered:
        lines.append(f"| {r['date']} | [{r['title']}]({r['path'].name}) | "
                     f"`{r['branch']}` | {r['handoff'] or '—'} |")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    TASKS.mkdir(parents=True, exist_ok=True)
    try:
        recs = load()
    except ValueError as e:
        print(f"Docs-Progress: MALFORMED -- {e}")
        return 1
    want = render(recs)
    have = INDEX.read_text(encoding="utf-8") if INDEX.exists() else None
    if a.check:
        if have != want:
            print("Docs-Progress: INDEX.md DIFFERS from a regeneration "
                  "(run `python tools/progress_index.py`)")
            return 1
        print(f"Docs-Progress: INDEX.md matches a regeneration "
              f"({len(recs)} records)")
        return 0
    INDEX.write_text(want, encoding="utf-8", newline="\n")
    print(f"Docs-Progress: wrote {INDEX.relative_to(ROOT)} ({len(recs)} records)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
